
export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const UPDATE_PROFILE_FORM = 'UPDATE_PROFILE_FORM';
export const UPDATE_SESSION_FORM = 'UPDATE_SESSION_FORM';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_SESSION_STATUS = 'SET_SESSION_STATUS';
